services:
    exam_bundle.question_admin:
        class: ExamBundle\Admin\QuestionAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, show_in_dashboard: false }
        arguments:
            - ~
            - ExamBundle\Entity\Question
            - ~
        calls:
            - [ setTranslationDomain, ["admin"]]