ActivityBundle\Entity\UserActivity:
    type:  entity
    table: users_activity
    repositoryClass: ActivityBundle\Repository\UserActivityRepository
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        score:
            type: integer
            nullable: false
        startDate:
            type: datetime
            nullable: false
    manyToOne:
        lesson:
            targetEntity: LessonBundle\Entity\Lesson
            inversedBy: activities
            joinColumn:
              name: lesson_id
              referencedColumnName: id
        user:
            targetEntity: UserBundle\Entity\User
            inversedBy: activities
            joinColumn:
              name: user_id
              referencedColumnName: id
          



            